#!/usr/bin/env bash

set -e
KERNEL_ELF="$1"
KERNEL_BIN="$KERNEL_ELF".bin
BUILD_DIR="$(dirname "$KERNEL_ELF")"
QEMU_ARGS=("${@:2}")

./scripts/prepare_kernel_accessories.sh "$KERNEL_ELF"

DEFAULT_QEMU_ARGS=(
  "-drive" "file=$BUILD_DIR/disk.img,if=sd,format=raw"
  "-initrd" "$BUILD_DIR/initrd.tar"
  "-dtb" "dtb_files/bcm2710-rpi-3-b.dtb"
  "-append" "earlycon=uart1"
)
qemu-system-aarch64 \
  -M raspi3b -serial null -serial stdio -semihosting "${DEFAULT_QEMU_ARGS[@]}" \
  -kernel "$KERNEL_BIN" -s -d int,unimp,guest_errors,mmu \
  "${QEMU_ARGS[@]}" 2>&1
